spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpamarket;
    username: sa
# Mac
#    password:
    # 윈도우
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 9090

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j